<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="f450_drone">
    
    <!-- #################### -->
    <!-- DJI F450 Quadcopter  -->
    <!-- #################### -->
    
    <!-- Properties -->
    <xacro:property name="frame_mass" value="0.280"/>
    <xacro:property name="motor_mass" value="0.055"/>
    <xacro:property name="propeller_mass" value="0.010"/>
    <xacro:property name="battery_mass" value="0.350"/>
    <xacro:property name="electronics_mass" value="0.200"/>
    
    <!-- Frame dimensions (meters) -->
    <xacro:property name="arm_length" value="0.225"/>
    <xacro:property name="arm_width" value="0.025"/>
    <xacro:property name="arm_height" value="0.010"/>
    <xacro:property name="center_radius" value="0.080"/>
    <xacro:property name="center_height" value="0.050"/>
    
    <!-- Motor dimensions -->
    <xacro:property name="motor_radius" value="0.014"/>
    <xacro:property name="motor_height" value="0.025"/>
    
    <!-- Propeller dimensions (10x4.5 inch = 254mm x 114mm) -->
    <xacro:property name="propeller_radius" value="0.127"/>
    <xacro:property name="propeller_height" value="0.005"/>
    
    <!-- Colors -->
    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
    </material>
    <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
    <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
    </material>
    
    <!-- Inertia macros -->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
                     iyy="${m*(3*r*r+h*h)/12}" iyz="0"
                     izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>
    
    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
                     iyy="${m*(x*x+z*z)/12}" iyz="0"
                     izz="${m*(x*x+y*y)/12}"/>
        </inertial>
    </xacro:macro>

    <!-- ==================== -->
    <!-- Base Link (Center)   -->
    <!-- ==================== -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${center_radius}" length="${center_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${center_radius}" length="${center_height}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="${frame_mass + battery_mass + electronics_mass}" r="${center_radius}" h="${center_height}"/>
    </link>
    
    <!-- Base footprint for navigation -->
    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </joint>
    
    <!-- ==================== -->
    <!-- Arm Macro            -->
    <!-- ==================== -->
    <xacro:macro name="arm" params="name angle color">
        <link name="${name}_arm">
            <visual>
                <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${arm_length} ${arm_width} ${arm_height}"/>
                </geometry>
                <material name="${color}"/>
            </visual>
            <collision>
                <origin xyz="${arm_length/2} 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${arm_length} ${arm_width} ${arm_height}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="0.030" x="${arm_length}" y="${arm_width}" z="${arm_height}"/>
        </link>
        
        <joint name="${name}_arm_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${name}_arm"/>
            <origin xyz="0 0 0" rpy="0 0 ${angle}"/>
        </joint>
    </xacro:macro>
    
    <!-- ==================== -->
    <!-- Motor Macro          -->
    <!-- ==================== -->
    <xacro:macro name="motor" params="name parent_arm angle">
        <link name="${name}_motor">
            <visual>
                <origin xyz="0 0 ${motor_height/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${motor_radius}" length="${motor_height}"/>
                </geometry>
                <material name="grey"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${motor_height/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${motor_radius}" length="${motor_height}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="${motor_mass}" r="${motor_radius}" h="${motor_height}"/>
        </link>
        
        <joint name="${name}_motor_joint" type="fixed">
            <parent link="${parent_arm}_arm"/>
            <child link="${name}_motor"/>
            <origin xyz="${arm_length} 0 ${arm_height/2}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
    
    <!-- ==================== -->
    <!-- Propeller Macro      -->
    <!-- ==================== -->
    <xacro:macro name="propeller" params="name parent_motor direction">
        <link name="${name}_propeller">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${propeller_radius}" length="${propeller_height}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${propeller_radius}" length="${propeller_height}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="${propeller_mass}" r="${propeller_radius}" h="${propeller_height}"/>
        </link>
        
        <joint name="${name}_propeller_joint" type="continuous">
            <parent link="${parent_motor}_motor"/>
            <child link="${name}_propeller"/>
            <origin xyz="0 0 ${motor_height + propeller_height/2}" rpy="0 0 0"/>
            <axis xyz="0 0 ${direction}"/>
            <limit effort="10" velocity="1000"/>
        </joint>
    </xacro:macro>

    <!-- ==================== -->
    <!-- Create Arms          -->
    <!-- ==================== -->
    <!-- X-configuration: arms at 45, 135, 225, 315 degrees -->
    <!-- Front-Right (1), Front-Left (2), Rear-Left (3), Rear-Right (4) -->
    
    <xacro:arm name="arm1" angle="${radians(45)}" color="white"/>
    <xacro:arm name="arm2" angle="${radians(135)}" color="red"/>
    <xacro:arm name="arm3" angle="${radians(225)}" color="white"/>
    <xacro:arm name="arm4" angle="${radians(315)}" color="red"/>
    
    <!-- ==================== -->
    <!-- Create Motors        -->
    <!-- ==================== -->
    <xacro:motor name="motor1" parent_arm="arm1" angle="${radians(45)}"/>
    <xacro:motor name="motor2" parent_arm="arm2" angle="${radians(135)}"/>
    <xacro:motor name="motor3" parent_arm="arm3" angle="${radians(225)}"/>
    <xacro:motor name="motor4" parent_arm="arm4" angle="${radians(315)}"/>
    
    <!-- ==================== -->
    <!-- Create Propellers    -->
    <!-- ==================== -->
    <!-- Alternating CW/CCW: 1-CW, 2-CCW, 3-CW, 4-CCW -->
    <xacro:propeller name="prop1" parent_motor="motor1" direction="1"/>
    <xacro:propeller name="prop2" parent_motor="motor2" direction="-1"/>
    <xacro:propeller name="prop3" parent_motor="motor3" direction="1"/>
    <xacro:propeller name="prop4" parent_motor="motor4" direction="-1"/>
    
    <!-- ==================== -->
    <!-- Camera Mount         -->
    <!-- ==================== -->
    <link name="camera_mount">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.03 0.04 0.02"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.03 0.04 0.02"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="0.020" x="0.03" y="0.04" z="0.02"/>
    </link>
    
    <joint name="camera_mount_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_mount"/>
        <origin xyz="${center_radius - 0.02} 0 -${center_height/2}" rpy="0 0.2 0"/>
    </joint>
    
    <!-- Camera optical frame -->
    <link name="camera_link"/>
    <joint name="camera_joint" type="fixed">
        <parent link="camera_mount"/>
        <child link="camera_link"/>
        <origin xyz="0.015 0 0" rpy="-1.5708 0 -1.5708"/>
    </joint>
    
    <link name="camera_optical_frame"/>
    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_optical_frame"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <!-- ==================== -->
    <!-- GPS Mount            -->
    <!-- ==================== -->
    <link name="gps_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.025" length="0.010"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.025" length="0.010"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.030" r="0.025" h="0.010"/>
    </link>
    
    <joint name="gps_joint" type="fixed">
        <parent link="base_link"/>
        <child link="gps_link"/>
        <origin xyz="0 0 ${center_height/2 + 0.05}" rpy="0 0 0"/>
    </joint>
    
    <!-- ==================== -->
    <!-- Flight Controller    -->
    <!-- ==================== -->
    <link name="flight_controller_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.044 0.084 0.015"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.044 0.084 0.015"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="0.040" x="0.044" y="0.084" z="0.015"/>
    </link>
    
    <joint name="flight_controller_joint" type="fixed">
        <parent link="base_link"/>
        <child link="flight_controller_link"/>
        <origin xyz="0 0 ${center_height/2 + 0.01}" rpy="0 0 0"/>
    </joint>
    
    <!-- ==================== -->
    <!-- IMU Link             -->
    <!-- ==================== -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
        <parent link="flight_controller_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

</robot>
